### ISSUE TITLE
Add 'About' section or another way to give overview of what tool does

### ISSUE THREAD

**Issue by tberardini** [tair/ifad-frontend#11]
This would lead to a pop-up window/new page with information on what the Whole Genome Snapshot does.  Alternatively, add some text at the top of the page, beneath the header that describes the tool.  If you like, we can provide the text.

Placeholder:

> Explore the state of annotation of the _Arabidopsis thaliana_ genome based on annotation status using the Gene Ontology (GO) aspects of Molecular Function, Biological Process, and Cellular Component.  yada yada yada

**Comment by jshearer** [comment]
Done :)

**Comment by lreiser** [comment]
closing per discussion today
