### ISSUE TITLE
Unchecking slices does not refresh calculations

### ISSUE THREAD

**Issue by lreiser** [tair/ifad-frontend#23]
Go to WGS
1. Click on a few pie slices from different pies (e.g. EXP MF, BP and CC)
2. Count adjusts according to additions
3. Unclick pie slice (e.g. MF EXP)
4. The counts/data does not change, the subtraction does not occur.

**Comment by lreiser** [comment]
I think this is fixed no?

**Comment by nicholastmosher** [comment]
Yes it is!
