### ISSUE TITLE
Filtering of psuedogenes is a 'backend' process not filter option

### ISSUE THREAD

**Issue by lreiser** [tair/ifad-frontend#32]
Please fix the filtering so that the psuedogenes are ALWAYS excluded from the WGS calculations. This should not be a visible option for users to select or deselect. 
The psuedogenes (ca 945) loci should be parsed out before even proceeding with the calculations.

I think perhaps this was not clear before what we meant by filtering. In this case, we mean to exclude psuedogenes from the WGS. this is because the are non functional  and will never have annotations.

**Comment by jshearer** [comment]
This is done -- the frontend only shows 2 options and all data excludes `pseudogene`
