### ISSUE TITLE
Clarify function of Any/All slider

### ISSUE THREAD

**Issue by lreiser** [tair/ifad-frontend#5]
This is basically toggling between AND/OR
Perhaps we can just label it as such...with the default being AND?

**Comment by tberardini** [comment]
Suggest that we use upper case and bold face to label the words 'AND' and 'OR' in the spelled out version of the Filter.

Example:

Filter: Biological Process - Unannotated **OR** Molecular Function - Annotated Unknown **OR** Molecular Function - Unannotated

**Comment by tberardini** [comment]
What about doing mixed queries?

Filter: Biological Process - Unannotated **AND** Molecular Function - Annotated Unknown **OR** Molecular Function - Unannotated

**Comment by lreiser** [comment]
@tberardini how important do you think ?For now we have either or we may just have to leave the more complex queries as an enhancement. Maybe we add AND plus OR as an enhancement and close this issue?

**Comment by tberardini** [comment]
> add AND plus OR as an enhancement and close this issue

I like this approach.

**Comment by lreiser** [comment]
closing issue per discussion today
