### ISSUE TITLE
Add metadata of source files to the page

### ISSUE THREAD

**Issue by tberardini** [tair/ifad-frontend#9]
Gene list metadata is in the header of the gene file
Annotation metadata is in the header of the annotation file

Could be a section at the bottom called "Data Sources" that also includes the source URL for each file.

**Comment by lreiser** [comment]
Example of metadata from GAF file

!gaf-version: 2.1
!
!Generated by GO Central
!
!Date Generated by GOC: 2019-10-07
!
!Header from tair source association file:
!=================================
!Project_name: The Arabidopsis Information Resource (TAIR)
!URL: http://www.arabidopsis.org
!Contact Email: curator@arabidopsis.org
!Last Updated: 2019-10-01
!=================================
!
!Header copied from paint_tair_valid.gaf
!=================================
!Created on Tue Jul 23 20:16:17 2019.
!PANTHER version: v.14.1.
!GO version: 2019-07-03.
!
!=================================
!
!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md
!

**Comment by jshearer** [comment]
Done :)

**Comment by lreiser** [comment]
closing per discussion today, suggested enhancement in new front end issue.
